name: Flake8 Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8
